version: '3.8'

services:
  ai-assistant:
    image: xhh1128/astro-ai:latest
    ports:
      - "4321:4321"
    environment:
      - PUBLIC_OPENAI_API_KEY=${PUBLIC_OPENAI_API_KEY}
      - PUBLIC_ANTHROPIC_API_KEY=${PUBLIC_ANTHROPIC_API_KEY}
      - PUBLIC_GOOGLE_API_KEY=${PUBLIC_GOOGLE_API_KEY}
      - PUBLIC_DEEPSEEK_API_KEY=${PUBLIC_DEEPSEEK_API_KEY}
      - PUBLIC_DEFAULT_MODEL=${PUBLIC_DEFAULT_MODEL}
      - PUBLIC_SHOW_SETTINGS=${PUBLIC_SHOW_SETTINGS}
      - PUBLIC_ACCESS_PASSWORD=${PUBLIC_ACCESS_PASSWORD}
      - HOST=0.0.0.0
      - PORT=4321
    restart: unless-stopped
